# Generated by Django 2.2.6 on 2019-11-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=265)),
                ('autor', models.CharField(max_length=50)),
                ('publicacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
